[workspace]
resolver = "2"
members = [ "mermaid", "plantuml",
    "sclang", # lil test language
    "scope-graph", # scope graph resolver
    "sg-parse", # parse using scope graph
]

[workspace.dependencies]

regex = "1.11.1"
scopegraphs= "0.3.3"
winnow = {version = "0.6.20"}
